### ISSUE TITLE
Trained Model For Evaluation?

### ISSUE THREAD

**Issue by Minotaur-CN** [murdockhou/MultiPoseNet-tensorflow#1]
Hi,

Could upload your trained model for evaluation?
Thanks in advance!

Regards

**Comment by murdockhou** [comment]
I have only trained the third part successfully and get nearly as same as the number of AP and AR on coco_val_2017 dataset. 

Keypoints detection and person detection part is till on training. Sorry for that because I'm a new guy about TF and DL.
